### ISSUE TITLE
No such file or directory: 'WebIDLGrammar.pkl'

### ISSUE THREAD

**Issue by victorlevasseur** [kripken/box2d.js#81]
Hi,

I'm trying to build box2d.js (to use ALLOW_MEMORY_GROWTH) on Linux. However, the build process stops because of this error : 

```
python /home/victor/Developpement/emsdk_portable/emscripten/master/tools/webidl_binder.py Box2D_v2.3.1.idl box2d_glue
Traceback (most recent call last):
  File "/home/victor/Developpement/emsdk_portable/emscripten/master/tools/webidl_binder.py", line 42, in <module>
    p = WebIDL.Parser()
  File "/home/victor/Developpement/emsdk_portable/emscripten/master/third_party/WebIDL.py", line 4919, in __init__
    picklefile='WebIDLGrammar.pkl')
  File "/usr/lib/python2.7/site-packages/ply/yacc.py", line 3253, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/usr/lib/python2.7/site-packages/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'WebIDLGrammar.pkl'
Makefile:92: recipe for target 'box2d_glue.cpp' failed
make: *** [box2d_glue.cpp] Error 1

```

**Comment by kripken** [comment]
Does webidl stuff work in general on that machine? try `./tests/runner.py test_webidl` in emscripten root. No idea how that could fail, but maybe reinstalling the latest sdk might help?
